# Generated by Django 2.2.4 on 2021-02-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
