# Generated by Django 2.2.4 on 2021-03-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_auto_20210226_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='quote',
        ),
    ]
